### PR TITLE
fixed popup issue

### PR DESCRIPTION
**Pull request by arbetts**

### CODE REVIEW

**Comment by peterborkuti** [comment]
ci:retest

**Comment by peterborkuti** [comment]
ci:retest

**Comment by peterborkuti** [comment]
Hi @arbetts,

I checked the [posi report](https://test-1-6.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/2451/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=0,label_exp=!master/functional-tomcat8-mysql56-jdk7/20)

However, I did not find any differences between master and your pull. But (what is peculiar) when I tested master with jenkins there were NO errors.
The linked POSI reports that when updating (=editing the second time) a web content via Web Content Display portlet's Configuration=>Edit web content menu, the pop up framework does not have a valid iframe id (the test searches for  editAsset_iframe_, but I found only ..._iframe_ in the id.

**Comment by arbetts** [comment]
that is strange ... i'll rebase and retest to see if we get the same errors. .. maybe something in the UI updated and the Id will be the same now?

**Comment by arbetts** [comment]
ci:retest

**Comment by arbetts** [comment]
i just realized why this is failing ... the mock class in the plugins needs to implement the method I added "setPlid(long)"

**Comment by arbetts** [comment]
i'll fix this and then resend

**Comment by arbetts** [comment]
working on fixing the error and rebasing

**Comment by arbetts** [comment]
https://github.com/peterborkuti/liferay-portal/pull/20

**Pull request closed without merging**
