### PR TITLE
LPS-76891 Implement summary screen

### PR DESCRIPTION
**Pull request by palius**
https://issues.liferay.com/browse/LPS-76891

### CODE REVIEW

**Comment by peterborkuti** [comment]
start reviewing

**Comment by peterborkuti** [comment]
Hi @palius,
I may messed up something, because I see this:
image

Is it OK?

**Comment by palius** [comment]
Hi @peterborkuti,

Well, if you ask me, that sould be an initial publication wich seems to be okay. I'll be in office soon.

**Comment by peterborkuti** [comment]
Because I could not test it (pages did not displayed at me), could you send it to QA to test it?

**Pull request closed without merging**
